2015-12-07 06:52:50 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/src/Controller/ArticlesController.php
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-07 06:57:36 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/src/Model/Table/ArticlesTable.php
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-07 06:58:48 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/src/Model/Table/ArticlesTable.php
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-07 06:58:51 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/src/Model/Table/ArticlesTable.php
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-07 07:00:53 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/src/Model/Table/ArticlesTable.php
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-07 07:07:38 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/src/Model/Table/ArticlesTable.php
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-07 07:30:01 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/src/Model/Table/ArticlesTable.php
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-07 07:34:35 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Users could not be found.
Exception Attributes: array (
  'class' => 'Users',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/users
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-07 08:59:52 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myblog.articles' doesn't exist
Request URL: /lab5/articles
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(96): Cake\Database\Schema\Collection->_reflect('Column', 'articles', Array, Object(Cake\Database\Schema\Table))
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(64): Cake\Database\Schema\Collection->describe('articles', Array)
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(423): Cake\Database\Schema\CachedCollection->describe('articles')
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(164): Cake\ORM\Table->schema()
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(122): Cake\ORM\Query->addDefaultTypes(Object(App\Model\Table\ArticlesTable))
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1228): Cake\ORM\Query->__construct(Object(Cake\Database\Connection), Object(App\Model\Table\ArticlesTable))
#6 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(931): Cake\ORM\Table->query()
#7 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Component\PaginatorComponent.php(166): Cake\ORM\Table->find('all', Array)
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(688): Cake\Controller\Component\PaginatorComponent->paginate(Object(App\Model\Table\ArticlesTable), Array)
#9 C:\xampp\htdocs\lab5\src\Controller\ArticlesController.php(21): Cake\Controller\Controller->paginate(Object(App\Model\Table\ArticlesTable))
#10 [internal function]: App\Controller\ArticlesController->index()
#11 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#12 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#13 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#14 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#15 {main}


2015-12-07 09:02:58 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Createarticles could not be found.
Exception Attributes: array (
  'class' => 'Createarticles',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/createarticles
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-07 09:07:31 Error: [Cake\Routing\Exception\MissingControllerException] Controller class CfreateArticles could not be found.
Exception Attributes: array (
  'class' => 'CfreateArticles',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/CfreateArticles
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-10 09:16:16 Error: [InvalidArgumentException] Articles is not associated with Categories
Request URL: /lab5/articles
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(250): Cake\ORM\EagerLoader->_normalizeContain(Object(App\Model\Table\ArticlesTable), 'Categories', Array, Array)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(358): Cake\ORM\EagerLoader->normalized(Object(App\Model\Table\ArticlesTable))
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(337): Cake\ORM\EagerLoader->attachableAssociations(Object(App\Model\Table\ArticlesTable))
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(872): Cake\ORM\EagerLoader->attachAssociations(Object(Cake\ORM\Query), Object(App\Model\Table\ArticlesTable), true)
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(828): Cake\ORM\Query->_transformQuery()
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Driver\Mysql.php(121): Cake\ORM\Query->sql()
#6 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(216): Cake\Database\Driver\Mysql->prepare(Object(Cake\ORM\Query))
#7 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(268): Cake\Database\Connection->prepare(Object(Cake\ORM\Query))
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(847): Cake\Database\Query->execute()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(272): Cake\ORM\Query->_execute()
#11 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(798): Cake\ORM\Query->_all()
#12 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Component\PaginatorComponent.php(171): Cake\ORM\Query->all()
#13 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(688): Cake\Controller\Component\PaginatorComponent->paginate(Object(App\Model\Table\ArticlesTable), Array)
#14 C:\xampp\htdocs\lab5\src\Controller\ArticlesController.php(24): Cake\Controller\Controller->paginate(Object(App\Model\Table\ArticlesTable))
#15 [internal function]: App\Controller\ArticlesController->index()
#16 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#17 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#18 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#19 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#20 {main}


2015-12-10 09:18:04 Error: [InvalidArgumentException] Articles is not associated with Categories
Request URL: /lab5/articles
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(250): Cake\ORM\EagerLoader->_normalizeContain(Object(App\Model\Table\ArticlesTable), 'Categories', Array, Array)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(358): Cake\ORM\EagerLoader->normalized(Object(App\Model\Table\ArticlesTable))
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\EagerLoader.php(337): Cake\ORM\EagerLoader->attachableAssociations(Object(App\Model\Table\ArticlesTable))
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(872): Cake\ORM\EagerLoader->attachAssociations(Object(Cake\ORM\Query), Object(App\Model\Table\ArticlesTable), true)
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(828): Cake\ORM\Query->_transformQuery()
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Driver\Mysql.php(121): Cake\ORM\Query->sql()
#6 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(216): Cake\Database\Driver\Mysql->prepare(Object(Cake\ORM\Query))
#7 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(268): Cake\Database\Connection->prepare(Object(Cake\ORM\Query))
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(847): Cake\Database\Query->execute()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(272): Cake\ORM\Query->_execute()
#11 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Query.php(798): Cake\ORM\Query->_all()
#12 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Component\PaginatorComponent.php(171): Cake\ORM\Query->all()
#13 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(688): Cake\Controller\Component\PaginatorComponent->paginate(Object(App\Model\Table\ArticlesTable), Array)
#14 C:\xampp\htdocs\lab5\src\Controller\ArticlesController.php(24): Cake\Controller\Controller->paginate(Object(App\Model\Table\ArticlesTable))
#15 [internal function]: App\Controller\ArticlesController->index()
#16 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#17 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#18 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#19 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#20 {main}


2015-12-10 09:22:44 Error: Fatal Error (4): syntax error, unexpected '$validator' (T_VARIABLE) in [C:\xampp\htdocs\lab5\src\Model\Table\UsersTable.php, line 43]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 09:22:44 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '$validator' (T_VARIABLE)
Request URL: /lab5/users
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 43)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 09:22:50 Error: Fatal Error (4): syntax error, unexpected '$validator' (T_VARIABLE) in [C:\xampp\htdocs\lab5\src\Model\Table\UsersTable.php, line 43]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 09:22:51 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '$validator' (T_VARIABLE)
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 43)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 09:30:34 Warning: Warning (4096): Argument 1 passed to App\Controller\UsersController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Event\EventManager.php on line 385 and defined in [C:\xampp\htdocs\lab5\src\Controller\UsersController.php, line 22]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 22
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 491
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-10 09:32:58 Warning: Warning (4096): Argument 1 passed to App\Controller\UsersController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Event\EventManager.php on line 385 and defined in [C:\xampp\htdocs\lab5\src\Controller\UsersController.php, line 22]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 22
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 491
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-10 09:32:59 Error: Fatal Error (4): syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING) in [C:\xampp\htdocs\lab5\src\Model\Entity\User.php, line 5]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 09:32:59 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)
Request URL: /lab5/users
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 5)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 09:34:05 Error: Fatal Error (4): syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING) in [C:\xampp\htdocs\lab5\src\Model\Entity\User.php, line 5]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 09:34:05 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)
Request URL: /lab5/users
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 5)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 09:34:20 Error: Fatal Error (4): syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING) in [C:\xampp\htdocs\lab5\src\Model\Entity\User.php, line 5]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 09:34:20 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 5)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 09:38:46 Error: Fatal Error (4): syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING) in [C:\xampp\htdocs\lab5\src\Model\Entity\User.php, line 5]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-12-10 09:38:46 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '\' (T_NS_SEPARATOR), expecting identifier (T_STRING)
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 5)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-10 09:39:12 Error: [InvalidArgumentException] Unknown type ""
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1566): Cake\Database\Type::build(NULL)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1499): Cake\ORM\Table->_newId(Array)
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(App\Model\Entity\User), Array)
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(App\Model\Entity\User), Object(ArrayObject))
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#6 C:\xampp\htdocs\lab5\src\Controller\UsersController.php(83): Cake\ORM\Table->save(Object(App\Model\Entity\User))
#7 [internal function]: App\Controller\UsersController->add()
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#11 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}


2015-12-10 09:39:48 Error: [InvalidArgumentException] Unknown type ""
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1566): Cake\Database\Type::build(NULL)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1499): Cake\ORM\Table->_newId(Array)
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(App\Model\Entity\User), Array)
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(App\Model\Entity\User), Object(ArrayObject))
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#6 C:\xampp\htdocs\lab5\src\Controller\UsersController.php(83): Cake\ORM\Table->save(Object(App\Model\Entity\User))
#7 [internal function]: App\Controller\UsersController->add()
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#11 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}


2015-12-10 09:41:09 Error: [InvalidArgumentException] Unknown type ""
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1566): Cake\Database\Type::build(NULL)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1499): Cake\ORM\Table->_newId(Array)
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(App\Model\Entity\User), Array)
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(App\Model\Entity\User), Object(ArrayObject))
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#6 C:\xampp\htdocs\lab5\src\Controller\UsersController.php(83): Cake\ORM\Table->save(Object(App\Model\Entity\User))
#7 [internal function]: App\Controller\UsersController->add()
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#11 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}


2015-12-10 09:41:14 Error: [InvalidArgumentException] Unknown type ""
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1566): Cake\Database\Type::build(NULL)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1499): Cake\ORM\Table->_newId(Array)
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(App\Model\Entity\User), Array)
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(App\Model\Entity\User), Object(ArrayObject))
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#6 C:\xampp\htdocs\lab5\src\Controller\UsersController.php(83): Cake\ORM\Table->save(Object(App\Model\Entity\User))
#7 [internal function]: App\Controller\UsersController->add()
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#11 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}


2015-12-10 09:41:34 Error: [InvalidArgumentException] Unknown type ""
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1566): Cake\Database\Type::build(NULL)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1499): Cake\ORM\Table->_newId(Array)
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(App\Model\Entity\User), Array)
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(App\Model\Entity\User), Object(ArrayObject))
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#6 C:\xampp\htdocs\lab5\src\Controller\UsersController.php(83): Cake\ORM\Table->save(Object(App\Model\Entity\User))
#7 [internal function]: App\Controller\UsersController->add()
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#11 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}


2015-12-10 09:43:38 Error: [InvalidArgumentException] Unknown type ""
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1566): Cake\Database\Type::build(NULL)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1499): Cake\ORM\Table->_newId(Array)
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(App\Model\Entity\User), Array)
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(App\Model\Entity\User), Object(ArrayObject))
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#6 C:\xampp\htdocs\lab5\src\Controller\UsersController.php(83): Cake\ORM\Table->save(Object(App\Model\Entity\User))
#7 [internal function]: App\Controller\UsersController->add()
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#11 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}


2015-12-10 09:48:27 Error: [InvalidArgumentException] Unknown type ""
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1566): Cake\Database\Type::build(NULL)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1499): Cake\ORM\Table->_newId(Array)
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(App\Model\Entity\User), Array)
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(App\Model\Entity\User), Object(ArrayObject))
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#6 C:\xampp\htdocs\lab5\src\Controller\UsersController.php(83): Cake\ORM\Table->save(Object(App\Model\Entity\User))
#7 [internal function]: App\Controller\UsersController->add()
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#11 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}


2015-12-10 09:51:00 Error: [InvalidArgumentException] Unknown type ""
Request URL: /lab5/users/add
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1566): Cake\Database\Type::build(NULL)
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1499): Cake\ORM\Table->_newId(Array)
#2 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(App\Model\Entity\User), Array)
#3 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(App\Model\Entity\User), Object(ArrayObject))
#4 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#5 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#6 C:\xampp\htdocs\lab5\src\Controller\UsersController.php(86): Cake\ORM\Table->save(Object(App\Model\Entity\User))
#7 [internal function]: App\Controller\UsersController->add()
#8 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#10 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#11 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}


2015-12-10 09:52:11 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /lab5/users/login
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-12-10 09:52:20 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /lab5/users/login
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-12-12 00:59:21 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /lab5/users/login
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-12-12 00:59:43 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::comments() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'comments',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /lab5/articles/comments
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-12-12 01:00:17 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Login could not be found.
Exception Attributes: array (
  'class' => 'Login',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /lab5/login
Stack Trace:
#0 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-12 01:00:42 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /lab5/users/login
Stack Trace:
#0 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\lab5\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\lab5\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


